#! /bin/sh
### BEGIN INIT INFO
# Provides:          bootsplash
# Required-Start:    
# Required-Stop:     glibc
# Default-Start:     S
# Default-Stop:
# Short-Description: Show this to console during boot
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

echo "Booting Debian for Cubox ..." >> /dev/tty0
