#! /bin/sh

### BEGIN INIT INFO
# Provides:          cubian-firstrun
# Required-Start:    $remote_fs
# Required-Stop:
# Should-Start:
# Default-Start:     S   
# Default-Stop:
# Short-Description: Script to run when cubian first starting
# Description:       Something needs to be done when cubian is
#                    starting at first time.
#                      
#                    1. regenerate ssh host key
#                    2. regenerate ajenti private key
### END INIT INFO

N=/etc/init.d/cubian-firstrun

set -e

do_expand_rootfs(){
        device="/dev/mmcblk0"
        (echo d; echo n; echo p; echo 1; echo ; echo; echo w;) | fdisk $device 
return 0
}

case "$1" in
  start)
	    reboot=false
		echo "First run. This process takes around 1 minute to finish..." >> /dev/tty0
		echo "Creating ssh keys..." >> /dev/tty0

	        NEWMAC=00:01:43:`openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//'`
                sed -e 's/ether/ether '$NEWMAC'/g' -i /etc/network/interfaces
                sed -e 's/ether/ether '$NEWMAC'/g' -i /etc/network/interfaces.hostapd
                # more output to console only in first run then to serial
                # sed -e 's/extraargs=console=tty0/extraargs=console=ttyS0,115200/g' -i /boot/uEnv.ct
                # sed -e 's/extraargs=console=tty0/extraargs=console=ttyS0,115200/g' -i /boot/uEnv.cb2
	        rm /etc/ssh/ssh_host*
                dpkg-reconfigure openssh-server 
		set +e
		#echo "Creating local sources list..." 
		#netselect-apt -s -n -o /etc/apt/sources.list >/dev/null 2>&1
		echo "Downloading packages list..." 
		apt-get update >/dev/null 2>&1
	        # echo "Updating all packages..." 
	        # apt-get -y upgrade >/dev/null 2>&1
                # apt-get -y clean >/dev/null 2>&1
		echo "Expanding rootfs..." >> /dev/tty0
		if do_expand_rootfs;then
			echo "Expanding rootfs success, rebooting automatically..." >> /dev/tty0
			/sbin/insserv cubian-resize2fs
	    	reboot=true
		else
			echo "Expanding rootfs has failed, see log files." 
		fi
		set -e
		/sbin/insserv -r cubian-firstrun
		if $reboot;then
			/sbin/reboot
		fi
        ;;
  *)
        echo "Usage: $N {start}" >&2
        exit 1
        ;;
esac

exit 0
